# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-14 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_authors', '0002_book_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(default='None'),
            preserve_default=False,
        ),
    ]
