# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-14 01:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0002_user_age_in_years'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='age_in_years',
            new_name='age',
        ),
    ]
